using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace .NET_MVC.Day-10
{
    public class 13_generate pdf files
    {
        
    }
}
------------------------------------
PDF file generation karna .NET me kaafi easy hai — bas sahi library chahiye. Sabse common aur powerful libraries:

✅ Popular Libraries for PDF Generation in .NET:
Library	Description
iText7 / iTextSharp	Powerful, but not free for commercial use
PdfSharp	Easy-to-use, open source
IronPDF	Paid, HTML to PDF
DinkToPdf	.NET wrapper for wkhtmltopdf (HTML ➝ PDF)
QuestPDF	Modern, free & open-source layout engine
----------------------------------------------------
✅ Example 1: PdfSharp (Basic PDF Generation)
-----------------
Install-Package PdfSharp
---------------------------------
using PdfSharp.Pdf;
using PdfSharp.Drawing;

public void GenerateSimplePdf()
{
    PdfDocument document = new PdfDocument();
    document.Info.Title = "Created with PdfSharp";

    PdfPage page = document.AddPage();
    XGraphics gfx = XGraphics.FromPdfPage(page);
    XFont font = new XFont("Verdana", 20, XFontStyle.Bold);

    gfx.DrawString("Hello PDF!", font, XBrushes.Black,
        new XRect(0, 0, page.Width, page.Height),
        XStringFormats.Center);

    document.Save("myfile.pdf");
}
--------------------------------------------------
✅ Example 2: QuestPDF (Modern + Layout Friendly)
---------
Install-Package QuestPDF
--------------------------
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

public class InvoiceDocument : IDocument
{
    public DocumentMetadata GetMetadata() => DocumentMetadata.Default;

    public void Compose(IDocumentContainer container)
    {
        container.Page(page =>
        {
            page.Margin(50);
            page.Header().Text("Invoice #123").FontSize(24);
            page.Content().Text("Thanks for your purchase!");
            page.Footer().AlignCenter().Text(x => x.Span("Generated by QuestPDF"));
        });
    }
}
----------------------------
// Generate PDF
var document = new InvoiceDocument();
document.GeneratePdf("invoice.pdf");
---------------------------------
✅ Example 3: HTML to PDF with DinkToPdf

-----------------------------------
Install-Package DinkToPdf

var converter = new SynchronizedConverter(new PdfTools());
var doc = new HtmlToPdfDocument()
{
    GlobalSettings = new GlobalSettings { PaperSize = PaperKind.A4 },
    Objects = { new ObjectSettings { HtmlContent = "<h1>Hello PDF</h1>" } }
};
converter.Convert(doc);
---------------------------------------------
✅ Use Cases
Invoice Generation 🧾

Report Exporting 📊

Certificates 🏆

Resume Builders 📄

Printable forms & receipts 🧾
---------------------------------------------------------------
🔐 Want to generate PDF in ASP.NET Core Controller?

[HttpGet]
public IActionResult GenerateInvoice()
{
    var document = new InvoiceDocument();
    var stream = new MemoryStream();
    document.GeneratePdf(stream);
    stream.Position = 0;

    return File(stream, "application/pdf", "Invoice.pdf");
}
